export const FETCH_EXPENSES_SUCCESS = "FETCH_EXPENSES_SUCCESS";
export const FETCH_EXPENSES_STARTED = "FETCH_EXPENSES_STARTED";
export const FETCH_EXPENSES_FAILURE = "FETCH_EXPENSES_FAILURE";

export const FETCH_EXPENSE_SUCCESS = "FETCH_EXPENSE_SUCCESS";
export const FETCH_EXPENSE_STARTED = "FETCH_EXPENSE_STARTED";
export const FETCH_EXPENSE_FAILURE = "FETCH_EXPENSE_FAILURE";

export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_STARTED = "FETCH_CATEGORIES_STARTED";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";

export const ADD_EXPENSE_SUCCESS = "ADD_EXPENSE_SUCCESS";
export const ADD_EXPENSE_STARTED = "ADD_EXPENSE_STARTED";
export const ADD_EXPENSE_FAILURE = "ADD_EXPENSE_FAILURE";

export const UPDATE_EXPENSE_SUCCESS = "UPDATE_EXPENSE_SUCCESS";
export const UPDATE_EXPENSE_STARTED = "UPDATE_EXPENSE_STARTED";
export const UPDATE_EXPENSE_FAILURE = "UPDATE_EXPENSE_FAILURE";

export const REMOVE_EXPENSE_SUCCESS = "REMOVE_EXPENSE_SUCCESS";
export const REMOVE_EXPENSE_STARTED = "REMOVE_EXPENSE_STARTED";
export const REMOVE_EXPENSE_FAILURE = "REMOVE_EXPENSE_FAILURE";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const GET_ERRORS = "GET_ERRORS";
